name: Artifacts Workflow
on: push

jobs:
    run-artifacts-workflow:
        runs-on: ubuntu-latest
        steps:
            - name: Math expression
              run: expr 2 + 2 > math-result.txt
            - name: Upload result file
              uses: actions/upload-artifact@v4
              with:
                   name: math-result
                   path: math-result.txt
    run-download-artifact:
        runs-on: ubuntu-latest
        needs: run-artifacts-workflow
        steps:
          - name: Download file
            uses: actions/download-artifact@v5
            with:
                name: math-result
          - name: Display file
            run: |
                 value= '$(cat math-result.txt)'
                 echo $value
