name : Cache Actions
on: workflow_dispatch

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            -  uses: actions/checkout@v5
            -  name: Cache node modules
               id: cache-steps
               uses: actions/cache@v4
               with:
                    path: ~/.npm 
                    key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
                    restore-keys: |
                        ${{ runner.os }}-npm-
                        ${{ runner.os }}-
            -  name: Display cache 
               run: echo '${{ toJson(steps.cache-steps.outputs)}}'
            -  name: Install dependencies
               run: npm install