name: "First Workflow"
on: [push]

jobs:
    run-first-command:
        runs-on: ubuntu-latest
        steps:
          - name:  Display some text
            run: echo "Some text"
          - name: Display node and npm version
            run: |
              node -v
              npm -v
