name: Functions in Workflow
on: push

jobs:
    job: 
        runs-on: ubuntu-latest
        steps:
            - name: Failure step
              id: error-step_1 
              run: exit 1 # Цей крок буде завершено з помилкою
            - name: Runs on canceled # Цей крок буде виконаний якщо workflow буде скасовано
              if: ${{ cancelled()}}
              run: echo "Runs on canceled"
            - name: Runs on any case # Цей крок буде виконаний завжди незалежно від статусу workflow
              if: ${{ always()}}
              run: echo "Runs on any case"
            - name: Runs on success # Цей крок буде виконаний якщо workflow буде завершено успішно
              if: ${{ success()}}
              run: echo "Runs on success"
            - name: Runs on Failure # Цей крок буде виконаний якщо workflow буде завершено з помилкою
              if: ${{ failure() && steps.error-step.conclusion == 'failure'}} # Це фільтр який перевіряє чи крок завершився з помилкою і чи крок error-step завершився з помилкою
              run: echo "Runs on Failure"
    second-job:
        runs-on: ubuntu-latest
        needs: job
        if: ${{ failure()}}
        steps:
            - name: Runs on failure second job
              run: echo "Jobs failed"