name: Secret Actions
on: [push]

jobs:
    run-secret-actions:
        runs-on: ubuntu-latest
        environment: "Staging" # Тут ми можемо використовувати environment variable для доступу до секретів 
        # За замовчуванням секрети та змінні доступні тільки ті що для репозиторію створені 
        steps:
            - name: Secret Actions
              run: |
                  echo '${{ vars.STATUS_NEW_REPO}}'
                  echo '${{ secrets.PASSWORD_SECRET_ONE}}'

                 